# Generated by Django 4.2.20 on 2025-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
