FROM node:18-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY --from=builder /app/dist /usr/share/nginx/html
RUN echo "window.env = { VITE_API_URL: '${VITE_API_URL}' };" > /usr/share/nginx/html/config.js

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]