FROM nginx:alpine

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY ./dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80
CMD ["/start.sh"]