# Étape 1 : Utiliser une image Python légère
FROM python:3.10-slim

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Étape 4 : Copier le code backend
COPY . .

# Étape 5 : Collecte des fichiers statiques
RUN python manage.py collectstatic --noinput

# Étape 6 : Exposer le port 8000
EXPOSE 8000

# Étape 7 : Lancer Gunicorn avec le bon chemin WSGI
CMD ["gunicorn", "--chdir", "/app", "--bind", "0.0.0.0:8000", "myapp.wsgi:application"]
